name: transcolar_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icone02.png"


flutter:
  uses-material-design: true
  
  assets:
    - assets/imagens/logo_colorida.png
    - assets/imagens/avatar_padrao.png
